# Generated by Django 5.1.5 on 2025-03-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_paiement_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='est_anticipation',
            field=models.BooleanField(default=False, verbose_name='Paiement anticipé'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='est_retroactif',
            field=models.BooleanField(default=False, verbose_name='Paiement rétroactif'),
        ),
    ]
