# Generated by Django 5.1.5 on 2025-02-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_eleve_date_naissance_eleve_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='annee_scolaire',
            field=models.CharField(default='2023-2024', help_text='Ex: 2023-2024', max_length=9),
        ),
    ]
