# Generated by Django 5.1.5 on 2025-02-13 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_etablissement_annee_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='telephone',
            field=models.CharField(default='+0000000000', help_text='Format recommandé : +221 XXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Entrez un numéro valide.', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
