# Generated by Django 5.1.5 on 2025-02-13 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0004_etablissement_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='telephone',
            field=models.CharField(default='+221 70 00 00', help_text='Format recommandé : +221 XXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Entrez un numéro valide.', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
