# Generated by Django 5.1.5 on 2025-03-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0005_remove_paiement_nombre_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='nombre_mois',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de mois concernés'),
        ),
    ]
