# Generated by Django 5.1.5 on 2025-03-02 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0006_paiement_nombre_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='annee_scolaire',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='bulletins.anneescolaire'),
            preserve_default=False,
        ),
    ]
