# Generated by Django 5.1.5 on 2025-02-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0008_note_appreciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('classe', models.CharField(blank=True, max_length=100, null=True)),
                ('etablissement', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('absences', models.JSONField(blank=True, null=True)),
                ('moyenne_annuelle', models.FloatField(default=0.0)),
                ('passe_classe', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.eleve')),
            ],
        ),
    ]
