# Generated by Django 5.1.5 on 2025-03-06 09:51

import bulletins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0009_archive_motif_archivage_alter_archive_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='absences',
            field=models.JSONField(blank=True, null=True, validators=[bulletins.models.validate_json]),
        ),
        migrations.AlterField(
            model_name='archive',
            name='mention_annuelle',
            field=models.CharField(blank=True, choices=[('Bien', 'Bien'), ('Assez bien', 'Assez bien'), ('Passable', 'Passable'), ('Très bien', 'Très bien'), ('Excellent', 'Excellent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='mention_semestre_1',
            field=models.CharField(blank=True, choices=[('Bien', 'Bien'), ('Assez bien', 'Assez bien'), ('Passable', 'Passable'), ('Très bien', 'Très bien'), ('Excellent', 'Excellent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='mention_semestre_2',
            field=models.CharField(blank=True, choices=[('Bien', 'Bien'), ('Assez bien', 'Assez bien'), ('Passable', 'Passable'), ('Très bien', 'Très bien'), ('Excellent', 'Excellent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='notes',
            field=models.JSONField(blank=True, null=True, validators=[bulletins.models.validate_json]),
        ),
    ]
