# Generated by Django 5.1.5 on 2025-02-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0009_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=9, unique=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='etablissement',
            name='annee_scolaire',
        ),
    ]
