# Generated by Django 5.1.5 on 2025-03-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0010_alter_archive_absences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('note_devoir', models.FloatField()),
                ('note_composition', models.FloatField()),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.matiere')),
            ],
        ),
    ]
