# Generated by Django 5.1.5 on 2025-02-14 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0010_anneescolaire_remove_etablissement_annee_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.classe'),
        ),
    ]
