# Generated by Django 5.1.5 on 2025-03-06 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0011_notearchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('inscription', "Frais d'inscription"), ('mensualite', 'Mensualité'), ('autre', 'Autre frais')], max_length=20)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('mobile', 'Mobile Money')], max_length=20)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('impaye', 'Impayé')], max_length=20)),
                ('annee_scolaire', models.CharField(max_length=10)),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives_paiements', to='bulletins.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='ScolariteArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('inscription', "Frais d'inscription"), ('mensualite', 'Mensualité'), ('autre', 'Autre frais')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annee_scolaire', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives_scolarite', to='bulletins.eleve')),
            ],
        ),
    ]
