# Generated by Django 5.1.5 on 2025-02-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0012_etablissement_annee_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='bulletins.anneescolaire'),
        ),
    ]
