# Generated by Django 5.1.5 on 2025-03-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0012_paiementarchive_scolaritearchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scolaritearchive',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='scolaritearchive',
            name='eleve',
        ),
        migrations.DeleteModel(
            name='PaiementArchive',
        ),
        migrations.DeleteModel(
            name='ScolariteArchive',
        ),
    ]
