# Generated by Django 5.1.5 on 2025-03-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0015_archivenote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveEmploiDuTemps',
        ),
        migrations.DeleteModel(
            name='ArchiveFrais',
        ),
    ]
