# Generated by Django 5.1.5 on 2025-02-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0016_etablissement_ia_etablissement_ief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='appreciation',
        ),
    ]
