# Generated by Django 5.1.5 on 2025-03-08 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0016_delete_archiveemploidutemps_delete_archivefrais'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementRestauré',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='Date de paiement')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire'), ('mobile', 'Mobile Money')], default='especes', max_length=20)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('impaye', 'Impayé')], default='paye', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Référence du paiement (ex: numéro de chèque)', max_length=100, null=True)),
                ('mois', models.IntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], help_text='Mois concerné (pour les paiements mensuels)', null=True)),
                ('est_anticipation', models.BooleanField(default=False, verbose_name='Paiement anticipé')),
                ('est_retroactif', models.BooleanField(default=False, verbose_name='Paiement rétroactif')),
                ('nombre_mois', models.PositiveIntegerField(default=1, verbose_name='Nombre de mois concernés')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_restaures', to='bulletins.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_restaures', to='bulletins.eleve')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_restaures', to='bulletins.frais')),
            ],
        ),
    ]
