# Generated by Django 5.1.5 on 2025-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0017_paiementrestauré'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementrestauré',
            name='annee_scolaire',
            field=models.CharField(max_length=9),
        ),
    ]
