# Generated by Django 5.1.5 on 2025-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0017_remove_note_appreciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='semestre',
            field=models.PositiveIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], default=1, verbose_name='Semestre'),
        ),
    ]
