# Generated by Django 5.1.5 on 2025-02-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0018_absence_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='choix_matiere_quatrieme',
            field=models.BooleanField(default=False, help_text='Si activé, les élèves de 4ème choisiront entre PC et une langue, comme en 3ème.'),
        ),
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('6e', 'Sixième'), ('5e', 'Cinquième'), ('4e', 'Quatrième'), ('3e', 'Troisième')], max_length=10, unique=True)),
                ('matieres_obligatoires', models.ManyToManyField(related_name='niveaux_obligatoires', to='bulletins.matiere')),
                ('matieres_optionnelles', models.ManyToManyField(blank=True, related_name='niveaux_optionnels', to='bulletins.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.niveauscolaire'),
        ),
        migrations.CreateModel(
            name='ChoixMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix_matieres', to='bulletins.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletins.matiere')),
            ],
            options={
                'unique_together': {('eleve', 'matiere')},
            },
        ),
    ]
