# Generated by Django 5.1.5 on 2025-03-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0018_alter_paiementrestauré_annee_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementrestauré',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_restaures', to='bulletins.anneescolaire'),
        ),
    ]
