# Generated by Django 5.1.5 on 2025-02-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0019_enseignant_choix_matiere_quatrieme_niveauscolaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='choix_matiere_quatrieme',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='choix_matiere_quatrieme',
            field=models.BooleanField(default=False, help_text='Si activé, les élèves de 4ème choisiront entre PC et une langue, comme en 3ème.'),
        ),
    ]
