# Generated by Django 5.1.5 on 2025-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0019_alter_paiementrestauré_annee_scolaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivepaiement',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='archivepaiement',
            name='frais',
        ),
        migrations.AddField(
            model_name='archivepaiement',
            name='eleve_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivepaiement',
            name='frais_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
