# Generated by Django 5.1.5 on 2025-03-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0020_remove_archivepaiement_eleve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivepaiement',
            name='eleve_id',
        ),
        migrations.RemoveField(
            model_name='archivepaiement',
            name='frais_id',
        ),
        migrations.AddField(
            model_name='archivepaiement',
            name='eleve',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivepaiement',
            name='frais',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
