# Generated by Django 5.1.5 on 2025-02-18 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0020_remove_enseignant_choix_matiere_quatrieme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='bulletins.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.classe'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletins.etablissement'),
        ),
    ]
