# Generated by Django 5.1.5 on 2025-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0021_remove_archivepaiement_eleve_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivepaiement',
            name='eleve',
        ),
        migrations.AddField(
            model_name='archivepaiement',
            name='eleve_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
