# Generated by Django 5.1.5 on 2025-02-18 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0021_alter_archive_annee_scolaire_alter_archive_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='date_archivage',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='archive',
            name='annee_scolaire',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='archive',
            name='classe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='etablissement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
