# Generated by Django 5.1.5 on 2025-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0022_archive_date_archivage_alter_archive_annee_scolaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='mention_annuelle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='mention_semestre_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='mention_semestre_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='rang_annuel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='rang_semestre_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='rang_semestre_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='total_points_semestre_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='archive',
            name='total_points_semestre_2',
            field=models.FloatField(default=0),
        ),
    ]
