# Generated by Django 5.1.5 on 2025-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0023_archive_mention_annuelle_archive_mention_semestre_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveauscolaire',
            name='ordre',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
