# Generated by Django 5.1.5 on 2025-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0024_alter_frais_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementrestauré',
            name='annee_scolaire',
            field=models.CharField(max_length=9),
        ),
    ]
