# Generated by Django 5.1.5 on 2025-02-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0024_niveauscolaire_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveauscolaire',
            name='ordre',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
