# Generated by Django 5.1.5 on 2025-02-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0025_alter_niveauscolaire_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='importance',
            field=models.CharField(choices=[('normale', 'Normale'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='normale', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='lue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
