# Generated by Django 5.1.5 on 2025-02-21 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0026_notification_importance_notification_lue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='importance',
            field=models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('importante', 'Importante')], default='normale', max_length=10),
        ),
    ]
