# Generated by Django 5.1.5 on 2025-03-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0026_alter_paiementrestauré_annee_scolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('type_frais', models.CharField(choices=[('inscription', "Frais d'inscription"), ('mensualite', 'Mensualité'), ('autre', 'Autre frais')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classe', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_archivage', models.DateTimeField()),
            ],
        ),
    ]
