# Generated by Django 5.1.5 on 2025-02-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0027_alter_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='importance',
            field=models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('importance', 'Importance')], default='normale', max_length=10),
        ),
    ]
