# Generated by Django 5.1.5 on 2025-03-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0028_fraisrestauré'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementrestauré',
            name='frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_restaures', to='bulletins.fraisrestauré'),
        ),
    ]
