# Generated by Django 5.1.5 on 2025-02-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0028_alter_notification_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_devoir',
        ),
        migrations.CreateModel(
            name='NoteDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(default=0, verbose_name='Note de devoir')),
                ('note_principale', models.BooleanField(default=False, verbose_name='Note principale')),
                ('semestre', models.PositiveIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], verbose_name='Semestre')),
                ('note_objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_devoirs', to='bulletins.note')),
            ],
        ),
    ]
