# Generated by Django 5.1.5 on 2025-02-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0029_remove_note_note_devoir_notedevoir'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_devoir',
            field=models.FloatField(default=0, verbose_name='Note des devoirs'),
        ),
        migrations.DeleteModel(
            name='NoteDevoir',
        ),
    ]
