# Generated by Django 5.1.5 on 2025-02-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0032_alter_niveauscolaire_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveauscolaire',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
