# Generated by Django 5.1.5 on 2025-02-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0033_alter_niveauscolaire_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveauscolaire',
            name='nom',
            field=models.CharField(choices=[('6e', '6ᵉ (Sixième)'), ('5e', '5ᵉ (Cinquième)'), ('4e', '4ᵉ (Quatrième)'), ('3e', '3ᵉ (Troisième)'), ('2nde', '2ⁿᵈᵉ (Seconde)'), ('1ere', '1ʳᵉ (Première)'), ('Tle', 'Tᵉʳᵐ (Terminale)')], max_length=10, unique=True),
        ),
    ]
